### ISSUE TITLE
cell size -12of-12 not working

### ISSUE THREAD

**Issue by yanko-ivanov** [tawian/tawian-frontend#1]
Hi there! :)
Great extension, it really adds a lot of useful stuff I found lacking in hackss. Kudos my good sir.

However, I noticed last night that you've missed the last cell size:
`.cell-11 { flex: 0 0 calc(100% * 11 / 12); min-width: calc(100% * 11 / 12); }` in /sass/_grid.scss  - the 12th one. Just my 2 cents.

**Comment by maxbeier** [comment]
Oh, good find, thanks :)
